In [1]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than or equal to 18
print(my_house >= 18)

# my_house less than your_house
print(my_house < your_house)

[False  True False False]
[False  True  True False]


In [4]:
bmi = np.array([21.852, 22.751, 21.75, 23.125, 21.441])
# logical_and()
# logical_or()
# logical_not()

print(np.logical_and(bmi > 21, bmi < 22))
# array([True, False, True, False, True], dtype=bool)

print(bmi[np.logical_and(bmi > 21, bmi < 22)])
# array([21.852, 21.75, 21.441])

[ True False  True False  True]
[21.852 21.75  21.441]


Filtering pandas dataframes

In [ ]:
import pandas as pd
brics = pd.read_csv("path/to/brics.csv", index_col = 0)

# get the series of booleans which fit the condition
is_huge = brics["area"] > 8

# print the boolean series
print(is_huge)

# print the countries which fit the condition
print(brics[is_huge])

In [ ]:
import numpy as np

np.logical_and(brics["area"] > 8, brics["area"] < 10)

brics[np.logical_and(brics["area"] > 8, brics["area"] < 10)]

In [ ]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Create car_maniac: observations that have a cars_per_cap over 500
cpc = cars['cars_per_cap']
many_cars = cpc > 500
car_maniac = cars[many_cars]

# Print car_maniac
print(car_maniac)